# https://www.elastic.co/guide/en/elasticsearch/reference/5.5/docker.html
# https://www.elastic.co/guide/en/kibana/5.5/_configuring_kibana_on_docker.html
version: '2.2'
services:
  elasticsearch553:
    build: elasticsearch/5.5.3/
    environment:
      - cluster.name=es553-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es553data1:/usr/share/elasticsearch/data
    ports:
      - 19200:9200
    networks:
      - es553net
  kibana553:
    image: docker.elastic.co/kibana/kibana:5.5.3
    environment:
      ELASTICSEARCH_URL: http://elasticsearch553:9200
    ports:
      - 15601:5601
    networks:
      - es553net

  elasticsearch612:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
    environment:
      - cluster.name=es612-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es612data1:/usr/share/elasticsearch/data
    ports:
      - 29200:9200
    networks:
      - es612net
  kibana612:
    build: kibana/6.1.2/
    environment:
      ELASTICSEARCH_URL: http://elasticsearch612:9200
    ports:
      - 25601:5601
    networks:
      - es612net

volumes:
  es553data1:
    driver: local
  es612data1:
    driver: local

networks:
  es553net:
  es612net:
